# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.23)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS opencv_cudev opencv_core opencv_cudaarithm opencv_flann opencv_imgproc opencv_intensity_transform opencv_ml opencv_phase_unwrapping opencv_plot opencv_quality opencv_reg opencv_surface_matching opencv_cudafilters opencv_cudaimgproc opencv_cudawarping opencv_dnn opencv_dnn_superres opencv_features2d opencv_fuzzy opencv_hfs opencv_img_hash opencv_imgcodecs opencv_line_descriptor opencv_photo opencv_saliency opencv_text opencv_videoio opencv_xphoto opencv_calib3d opencv_cudacodec opencv_cudafeatures2d opencv_cudastereo opencv_datasets opencv_highgui opencv_mcc opencv_objdetect opencv_rapid opencv_rgbd opencv_shape opencv_structured_light opencv_video opencv_xfeatures2d opencv_ximgproc opencv_xobjdetect opencv_aruco opencv_bgsegm opencv_bioinspired opencv_ccalib opencv_cudabgsegm opencv_cudalegacy opencv_cudaobjdetect opencv_dnn_objdetect opencv_dpm opencv_face opencv_gapi opencv_optflow opencv_stitching opencv_tracking opencv_cudaoptflow opencv_stereo opencv_superres opencv_videostab)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target opencv_cudev
add_library(opencv_cudev SHARED IMPORTED)

# Create imported target opencv_core
add_library(opencv_core SHARED IMPORTED)

set_target_properties(opencv_core PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev"
)

# Create imported target opencv_cudaarithm
add_library(opencv_cudaarithm SHARED IMPORTED)

set_target_properties(opencv_cudaarithm PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core"
)

# Create imported target opencv_flann
add_library(opencv_flann SHARED IMPORTED)

set_target_properties(opencv_flann PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core"
)

# Create imported target opencv_imgproc
add_library(opencv_imgproc SHARED IMPORTED)

set_target_properties(opencv_imgproc PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core"
)

# Create imported target opencv_intensity_transform
add_library(opencv_intensity_transform SHARED IMPORTED)

set_target_properties(opencv_intensity_transform PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_imgproc"
)

# Create imported target opencv_ml
add_library(opencv_ml SHARED IMPORTED)

set_target_properties(opencv_ml PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core"
)

# Create imported target opencv_phase_unwrapping
add_library(opencv_phase_unwrapping SHARED IMPORTED)

set_target_properties(opencv_phase_unwrapping PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_imgproc"
)

# Create imported target opencv_plot
add_library(opencv_plot SHARED IMPORTED)

set_target_properties(opencv_plot PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_imgproc"
)

# Create imported target opencv_quality
add_library(opencv_quality SHARED IMPORTED)

set_target_properties(opencv_quality PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_imgproc;opencv_ml"
)

# Create imported target opencv_reg
add_library(opencv_reg SHARED IMPORTED)

set_target_properties(opencv_reg PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_imgproc"
)

# Create imported target opencv_surface_matching
add_library(opencv_surface_matching SHARED IMPORTED)

set_target_properties(opencv_surface_matching PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann"
)

# Create imported target opencv_cudafilters
add_library(opencv_cudafilters SHARED IMPORTED)

set_target_properties(opencv_cudafilters PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_cudaarithm;opencv_imgproc"
)

# Create imported target opencv_cudaimgproc
add_library(opencv_cudaimgproc SHARED IMPORTED)

set_target_properties(opencv_cudaimgproc PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_cudaarithm;opencv_imgproc;opencv_cudafilters"
)

# Create imported target opencv_cudawarping
add_library(opencv_cudawarping SHARED IMPORTED)

set_target_properties(opencv_cudawarping PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_imgproc"
)

# Create imported target opencv_dnn
add_library(opencv_dnn SHARED IMPORTED)

set_target_properties(opencv_dnn PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_imgproc"
)

# Create imported target opencv_dnn_superres
add_library(opencv_dnn_superres SHARED IMPORTED)

set_target_properties(opencv_dnn_superres PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_imgproc;opencv_ml;opencv_quality;opencv_dnn"
)

# Create imported target opencv_features2d
add_library(opencv_features2d SHARED IMPORTED)

set_target_properties(opencv_features2d PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_imgproc"
)

# Create imported target opencv_fuzzy
add_library(opencv_fuzzy SHARED IMPORTED)

set_target_properties(opencv_fuzzy PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_imgproc"
)

# Create imported target opencv_hfs
add_library(opencv_hfs SHARED IMPORTED)

set_target_properties(opencv_hfs PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_imgproc"
)

# Create imported target opencv_img_hash
add_library(opencv_img_hash SHARED IMPORTED)

set_target_properties(opencv_img_hash PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_imgproc"
)

# Create imported target opencv_imgcodecs
add_library(opencv_imgcodecs SHARED IMPORTED)

set_target_properties(opencv_imgcodecs PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_imgproc"
)

# Create imported target opencv_line_descriptor
add_library(opencv_line_descriptor SHARED IMPORTED)

set_target_properties(opencv_line_descriptor PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_features2d"
)

# Create imported target opencv_photo
add_library(opencv_photo SHARED IMPORTED)

set_target_properties(opencv_photo PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_cudaarithm;opencv_imgproc;opencv_cudafilters;opencv_cudaimgproc"
)

# Create imported target opencv_saliency
add_library(opencv_saliency SHARED IMPORTED)

set_target_properties(opencv_saliency PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_features2d"
)

# Create imported target opencv_text
add_library(opencv_text SHARED IMPORTED)

set_target_properties(opencv_text PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_dnn;opencv_features2d"
)

# Create imported target opencv_videoio
add_library(opencv_videoio SHARED IMPORTED)

set_target_properties(opencv_videoio PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_imgproc;opencv_imgcodecs"
)

# Create imported target opencv_xphoto
add_library(opencv_xphoto SHARED IMPORTED)

set_target_properties(opencv_xphoto PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_cudaarithm;opencv_imgproc;opencv_cudafilters;opencv_cudaimgproc;opencv_photo"
)

# Create imported target opencv_calib3d
add_library(opencv_calib3d SHARED IMPORTED)

set_target_properties(opencv_calib3d PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_features2d"
)

# Create imported target opencv_cudacodec
add_library(opencv_cudacodec SHARED IMPORTED)

set_target_properties(opencv_cudacodec PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_imgproc;opencv_imgcodecs;opencv_videoio"
)

# Create imported target opencv_cudafeatures2d
add_library(opencv_cudafeatures2d SHARED IMPORTED)

set_target_properties(opencv_cudafeatures2d PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_imgproc;opencv_cudafilters;opencv_cudawarping;opencv_features2d"
)

# Create imported target opencv_cudastereo
add_library(opencv_cudastereo SHARED IMPORTED)

set_target_properties(opencv_cudastereo PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_features2d;opencv_calib3d"
)

# Create imported target opencv_datasets
add_library(opencv_datasets SHARED IMPORTED)

set_target_properties(opencv_datasets PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_dnn;opencv_features2d;opencv_imgcodecs;opencv_text"
)

# Create imported target opencv_highgui
add_library(opencv_highgui SHARED IMPORTED)

set_target_properties(opencv_highgui PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_imgproc;opencv_imgcodecs;opencv_videoio"
)

# Create imported target opencv_mcc
add_library(opencv_mcc SHARED IMPORTED)

set_target_properties(opencv_mcc PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_imgproc;opencv_cudafilters;opencv_cudaimgproc;opencv_dnn;opencv_features2d;opencv_photo;opencv_calib3d"
)

# Create imported target opencv_objdetect
add_library(opencv_objdetect SHARED IMPORTED)

set_target_properties(opencv_objdetect PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_features2d;opencv_calib3d"
)

# Create imported target opencv_rapid
add_library(opencv_rapid SHARED IMPORTED)

set_target_properties(opencv_rapid PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_features2d;opencv_calib3d"
)

# Create imported target opencv_rgbd
add_library(opencv_rgbd SHARED IMPORTED)

set_target_properties(opencv_rgbd PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_features2d;opencv_calib3d"
)

# Create imported target opencv_shape
add_library(opencv_shape SHARED IMPORTED)

set_target_properties(opencv_shape PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_features2d;opencv_calib3d"
)

# Create imported target opencv_structured_light
add_library(opencv_structured_light SHARED IMPORTED)

set_target_properties(opencv_structured_light PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_phase_unwrapping;opencv_features2d;opencv_calib3d"
)

# Create imported target opencv_video
add_library(opencv_video SHARED IMPORTED)

set_target_properties(opencv_video PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_features2d;opencv_calib3d"
)

# Create imported target opencv_xfeatures2d
add_library(opencv_xfeatures2d SHARED IMPORTED)

set_target_properties(opencv_xfeatures2d PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_imgproc;opencv_ml;opencv_features2d;opencv_calib3d;opencv_shape"
)

# Create imported target opencv_ximgproc
add_library(opencv_ximgproc SHARED IMPORTED)

set_target_properties(opencv_ximgproc PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_features2d;opencv_imgcodecs;opencv_calib3d;opencv_video"
)

# Create imported target opencv_xobjdetect
add_library(opencv_xobjdetect SHARED IMPORTED)

set_target_properties(opencv_xobjdetect PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_features2d;opencv_imgcodecs;opencv_calib3d;opencv_objdetect"
)

# Create imported target opencv_aruco
add_library(opencv_aruco SHARED IMPORTED)

set_target_properties(opencv_aruco PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_features2d;opencv_calib3d"
)

# Create imported target opencv_bgsegm
add_library(opencv_bgsegm SHARED IMPORTED)

set_target_properties(opencv_bgsegm PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_features2d;opencv_calib3d;opencv_video"
)

# Create imported target opencv_bioinspired
add_library(opencv_bioinspired SHARED IMPORTED)

set_target_properties(opencv_bioinspired PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_imgproc;opencv_imgcodecs;opencv_videoio;opencv_highgui"
)

# Create imported target opencv_ccalib
add_library(opencv_ccalib SHARED IMPORTED)

set_target_properties(opencv_ccalib PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_features2d;opencv_imgcodecs;opencv_videoio;opencv_calib3d;opencv_highgui"
)

# Create imported target opencv_cudabgsegm
add_library(opencv_cudabgsegm SHARED IMPORTED)

set_target_properties(opencv_cudabgsegm PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_features2d;opencv_calib3d;opencv_video"
)

# Create imported target opencv_cudalegacy
add_library(opencv_cudalegacy SHARED IMPORTED)

set_target_properties(opencv_cudalegacy PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_imgproc;opencv_cudafilters;opencv_cudaimgproc;opencv_features2d;opencv_calib3d;opencv_objdetect;opencv_video"
)

# Create imported target opencv_cudaobjdetect
add_library(opencv_cudaobjdetect SHARED IMPORTED)

set_target_properties(opencv_cudaobjdetect PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_imgproc;opencv_cudafilters;opencv_cudaimgproc;opencv_cudawarping;opencv_features2d;opencv_calib3d;opencv_objdetect;opencv_video;opencv_cudalegacy"
)

# Create imported target opencv_dnn_objdetect
add_library(opencv_dnn_objdetect SHARED IMPORTED)

set_target_properties(opencv_dnn_objdetect PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_imgproc;opencv_dnn;opencv_imgcodecs;opencv_videoio;opencv_highgui"
)

# Create imported target opencv_dpm
add_library(opencv_dpm SHARED IMPORTED)

set_target_properties(opencv_dpm PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_features2d;opencv_imgcodecs;opencv_videoio;opencv_calib3d;opencv_highgui;opencv_objdetect"
)

# Create imported target opencv_face
add_library(opencv_face SHARED IMPORTED)

set_target_properties(opencv_face PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_imgproc;opencv_cudafilters;opencv_cudaimgproc;opencv_features2d;opencv_photo;opencv_calib3d;opencv_objdetect"
)

# Create imported target opencv_gapi
add_library(opencv_gapi SHARED IMPORTED)

set_target_properties(opencv_gapi PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_features2d;opencv_calib3d;opencv_video"
)

# Create imported target opencv_optflow
add_library(opencv_optflow SHARED IMPORTED)

set_target_properties(opencv_optflow PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_features2d;opencv_imgcodecs;opencv_calib3d;opencv_video;opencv_ximgproc"
)

# Create imported target opencv_stitching
add_library(opencv_stitching SHARED IMPORTED)

set_target_properties(opencv_stitching PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_imgproc;opencv_ml;opencv_cudafilters;opencv_cudaimgproc;opencv_cudawarping;opencv_features2d;opencv_calib3d;opencv_cudafeatures2d;opencv_objdetect;opencv_shape;opencv_video;opencv_xfeatures2d;opencv_cudalegacy"
)

# Create imported target opencv_tracking
add_library(opencv_tracking SHARED IMPORTED)

set_target_properties(opencv_tracking PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_plot;opencv_dnn;opencv_features2d;opencv_imgcodecs;opencv_text;opencv_calib3d;opencv_datasets;opencv_video"
)

# Create imported target opencv_cudaoptflow
add_library(opencv_cudaoptflow SHARED IMPORTED)

set_target_properties(opencv_cudaoptflow PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_imgproc;opencv_cudafilters;opencv_cudaimgproc;opencv_cudawarping;opencv_features2d;opencv_imgcodecs;opencv_calib3d;opencv_objdetect;opencv_video;opencv_ximgproc;opencv_cudalegacy;opencv_optflow"
)

# Create imported target opencv_stereo
add_library(opencv_stereo SHARED IMPORTED)

set_target_properties(opencv_stereo PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_plot;opencv_dnn;opencv_features2d;opencv_imgcodecs;opencv_text;opencv_calib3d;opencv_datasets;opencv_video;opencv_tracking"
)

# Create imported target opencv_superres
add_library(opencv_superres SHARED IMPORTED)

set_target_properties(opencv_superres PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_imgproc;opencv_cudafilters;opencv_cudaimgproc;opencv_cudawarping;opencv_features2d;opencv_imgcodecs;opencv_videoio;opencv_calib3d;opencv_cudacodec;opencv_objdetect;opencv_video;opencv_ximgproc;opencv_cudalegacy;opencv_optflow;opencv_cudaoptflow"
)

# Create imported target opencv_videostab
add_library(opencv_videostab SHARED IMPORTED)

set_target_properties(opencv_videostab PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_imgproc;opencv_cudafilters;opencv_cudaimgproc;opencv_cudawarping;opencv_features2d;opencv_imgcodecs;opencv_photo;opencv_videoio;opencv_calib3d;opencv_objdetect;opencv_video;opencv_ximgproc;opencv_cudalegacy;opencv_optflow;opencv_cudaoptflow"
)

# Import target "opencv_cudev" for configuration "Debug"
set_property(TARGET opencv_cudev APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_cudev PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_cudev450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_cudev450d.dll"
  )

# Import target "opencv_core" for configuration "Debug"
set_property(TARGET opencv_core APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_core PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_core450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_core450d.dll"
  )

# Import target "opencv_cudaarithm" for configuration "Debug"
set_property(TARGET opencv_cudaarithm APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_cudaarithm PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_cudaarithm450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_cudaarithm450d.dll"
  )

# Import target "opencv_flann" for configuration "Debug"
set_property(TARGET opencv_flann APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_flann PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_flann450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_flann450d.dll"
  )

# Import target "opencv_imgproc" for configuration "Debug"
set_property(TARGET opencv_imgproc APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_imgproc PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_imgproc450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_imgproc450d.dll"
  )

# Import target "opencv_intensity_transform" for configuration "Debug"
set_property(TARGET opencv_intensity_transform APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_intensity_transform PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_intensity_transform450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_intensity_transform450d.dll"
  )

# Import target "opencv_ml" for configuration "Debug"
set_property(TARGET opencv_ml APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_ml PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_ml450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_ml450d.dll"
  )

# Import target "opencv_phase_unwrapping" for configuration "Debug"
set_property(TARGET opencv_phase_unwrapping APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_phase_unwrapping PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_phase_unwrapping450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_phase_unwrapping450d.dll"
  )

# Import target "opencv_plot" for configuration "Debug"
set_property(TARGET opencv_plot APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_plot PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_plot450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_plot450d.dll"
  )

# Import target "opencv_quality" for configuration "Debug"
set_property(TARGET opencv_quality APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_quality PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_quality450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_quality450d.dll"
  )

# Import target "opencv_reg" for configuration "Debug"
set_property(TARGET opencv_reg APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_reg PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_reg450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_reg450d.dll"
  )

# Import target "opencv_surface_matching" for configuration "Debug"
set_property(TARGET opencv_surface_matching APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_surface_matching PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_surface_matching450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_surface_matching450d.dll"
  )

# Import target "opencv_cudafilters" for configuration "Debug"
set_property(TARGET opencv_cudafilters APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_cudafilters PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_cudafilters450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_cudafilters450d.dll"
  )

# Import target "opencv_cudaimgproc" for configuration "Debug"
set_property(TARGET opencv_cudaimgproc APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_cudaimgproc PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_cudaimgproc450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_cudaimgproc450d.dll"
  )

# Import target "opencv_cudawarping" for configuration "Debug"
set_property(TARGET opencv_cudawarping APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_cudawarping PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_cudawarping450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_cudawarping450d.dll"
  )

# Import target "opencv_dnn" for configuration "Debug"
set_property(TARGET opencv_dnn APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_dnn PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_dnn450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_dnn450d.dll"
  )

# Import target "opencv_dnn_superres" for configuration "Debug"
set_property(TARGET opencv_dnn_superres APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_dnn_superres PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_dnn_superres450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_dnn_superres450d.dll"
  )

# Import target "opencv_features2d" for configuration "Debug"
set_property(TARGET opencv_features2d APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_features2d PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_features2d450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_features2d450d.dll"
  )

# Import target "opencv_fuzzy" for configuration "Debug"
set_property(TARGET opencv_fuzzy APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_fuzzy PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_fuzzy450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_fuzzy450d.dll"
  )

# Import target "opencv_hfs" for configuration "Debug"
set_property(TARGET opencv_hfs APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_hfs PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_hfs450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_hfs450d.dll"
  )

# Import target "opencv_img_hash" for configuration "Debug"
set_property(TARGET opencv_img_hash APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_img_hash PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_img_hash450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_img_hash450d.dll"
  )

# Import target "opencv_imgcodecs" for configuration "Debug"
set_property(TARGET opencv_imgcodecs APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_imgcodecs PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_imgcodecs450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_imgcodecs450d.dll"
  )

# Import target "opencv_line_descriptor" for configuration "Debug"
set_property(TARGET opencv_line_descriptor APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_line_descriptor PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_line_descriptor450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_line_descriptor450d.dll"
  )

# Import target "opencv_photo" for configuration "Debug"
set_property(TARGET opencv_photo APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_photo PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_photo450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_photo450d.dll"
  )

# Import target "opencv_saliency" for configuration "Debug"
set_property(TARGET opencv_saliency APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_saliency PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_saliency450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_saliency450d.dll"
  )

# Import target "opencv_text" for configuration "Debug"
set_property(TARGET opencv_text APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_text PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_text450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_text450d.dll"
  )

# Import target "opencv_videoio" for configuration "Debug"
set_property(TARGET opencv_videoio APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_videoio PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_videoio450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_videoio450d.dll"
  )

# Import target "opencv_xphoto" for configuration "Debug"
set_property(TARGET opencv_xphoto APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_xphoto PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_xphoto450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_xphoto450d.dll"
  )

# Import target "opencv_calib3d" for configuration "Debug"
set_property(TARGET opencv_calib3d APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_calib3d PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_calib3d450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_calib3d450d.dll"
  )

# Import target "opencv_cudacodec" for configuration "Debug"
set_property(TARGET opencv_cudacodec APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_cudacodec PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_cudacodec450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_cudacodec450d.dll"
  )

# Import target "opencv_cudafeatures2d" for configuration "Debug"
set_property(TARGET opencv_cudafeatures2d APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_cudafeatures2d PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_cudafeatures2d450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_cudafeatures2d450d.dll"
  )

# Import target "opencv_cudastereo" for configuration "Debug"
set_property(TARGET opencv_cudastereo APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_cudastereo PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_cudastereo450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_cudastereo450d.dll"
  )

# Import target "opencv_datasets" for configuration "Debug"
set_property(TARGET opencv_datasets APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_datasets PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_datasets450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_datasets450d.dll"
  )

# Import target "opencv_highgui" for configuration "Debug"
set_property(TARGET opencv_highgui APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_highgui PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_highgui450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_highgui450d.dll"
  )

# Import target "opencv_mcc" for configuration "Debug"
set_property(TARGET opencv_mcc APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_mcc PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_mcc450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_mcc450d.dll"
  )

# Import target "opencv_objdetect" for configuration "Debug"
set_property(TARGET opencv_objdetect APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_objdetect PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_objdetect450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_objdetect450d.dll"
  )

# Import target "opencv_rapid" for configuration "Debug"
set_property(TARGET opencv_rapid APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_rapid PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_rapid450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_rapid450d.dll"
  )

# Import target "opencv_rgbd" for configuration "Debug"
set_property(TARGET opencv_rgbd APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_rgbd PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_rgbd450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_rgbd450d.dll"
  )

# Import target "opencv_shape" for configuration "Debug"
set_property(TARGET opencv_shape APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_shape PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_shape450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_shape450d.dll"
  )

# Import target "opencv_structured_light" for configuration "Debug"
set_property(TARGET opencv_structured_light APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_structured_light PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_structured_light450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_structured_light450d.dll"
  )

# Import target "opencv_video" for configuration "Debug"
set_property(TARGET opencv_video APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_video PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_video450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_video450d.dll"
  )

# Import target "opencv_xfeatures2d" for configuration "Debug"
set_property(TARGET opencv_xfeatures2d APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_xfeatures2d PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_xfeatures2d450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_xfeatures2d450d.dll"
  )

# Import target "opencv_ximgproc" for configuration "Debug"
set_property(TARGET opencv_ximgproc APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_ximgproc PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_ximgproc450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_ximgproc450d.dll"
  )

# Import target "opencv_xobjdetect" for configuration "Debug"
set_property(TARGET opencv_xobjdetect APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_xobjdetect PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_xobjdetect450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_xobjdetect450d.dll"
  )

# Import target "opencv_aruco" for configuration "Debug"
set_property(TARGET opencv_aruco APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_aruco PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_aruco450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_aruco450d.dll"
  )

# Import target "opencv_bgsegm" for configuration "Debug"
set_property(TARGET opencv_bgsegm APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_bgsegm PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_bgsegm450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_bgsegm450d.dll"
  )

# Import target "opencv_bioinspired" for configuration "Debug"
set_property(TARGET opencv_bioinspired APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_bioinspired PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_bioinspired450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_bioinspired450d.dll"
  )

# Import target "opencv_ccalib" for configuration "Debug"
set_property(TARGET opencv_ccalib APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_ccalib PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_ccalib450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_ccalib450d.dll"
  )

# Import target "opencv_cudabgsegm" for configuration "Debug"
set_property(TARGET opencv_cudabgsegm APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_cudabgsegm PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_cudabgsegm450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_cudabgsegm450d.dll"
  )

# Import target "opencv_cudalegacy" for configuration "Debug"
set_property(TARGET opencv_cudalegacy APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_cudalegacy PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_cudalegacy450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_cudalegacy450d.dll"
  )

# Import target "opencv_cudaobjdetect" for configuration "Debug"
set_property(TARGET opencv_cudaobjdetect APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_cudaobjdetect PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_cudaobjdetect450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_cudaobjdetect450d.dll"
  )

# Import target "opencv_dnn_objdetect" for configuration "Debug"
set_property(TARGET opencv_dnn_objdetect APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_dnn_objdetect PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_dnn_objdetect450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_dnn_objdetect450d.dll"
  )

# Import target "opencv_dpm" for configuration "Debug"
set_property(TARGET opencv_dpm APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_dpm PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_dpm450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_dpm450d.dll"
  )

# Import target "opencv_face" for configuration "Debug"
set_property(TARGET opencv_face APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_face PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_face450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_face450d.dll"
  )

# Import target "opencv_gapi" for configuration "Debug"
set_property(TARGET opencv_gapi APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_gapi PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_gapi450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_gapi450d.dll"
  )

# Import target "opencv_optflow" for configuration "Debug"
set_property(TARGET opencv_optflow APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_optflow PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_optflow450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_optflow450d.dll"
  )

# Import target "opencv_stitching" for configuration "Debug"
set_property(TARGET opencv_stitching APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_stitching PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_stitching450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_stitching450d.dll"
  )

# Import target "opencv_tracking" for configuration "Debug"
set_property(TARGET opencv_tracking APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_tracking PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_tracking450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_tracking450d.dll"
  )

# Import target "opencv_cudaoptflow" for configuration "Debug"
set_property(TARGET opencv_cudaoptflow APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_cudaoptflow PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_cudaoptflow450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_cudaoptflow450d.dll"
  )

# Import target "opencv_stereo" for configuration "Debug"
set_property(TARGET opencv_stereo APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_stereo PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_stereo450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_stereo450d.dll"
  )

# Import target "opencv_superres" for configuration "Debug"
set_property(TARGET opencv_superres APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_superres PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_superres450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_superres450d.dll"
  )

# Import target "opencv_videostab" for configuration "Debug"
set_property(TARGET opencv_videostab APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_videostab PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Debug/opencv_videostab450d.lib"
  IMPORTED_LOCATION_DEBUG "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Debug/opencv_videostab450d.dll"
  )

# Import target "opencv_cudev" for configuration "Release"
set_property(TARGET opencv_cudev APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudev PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_cudev450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_cudev450.dll"
  )

# Import target "opencv_core" for configuration "Release"
set_property(TARGET opencv_core APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_core PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_core450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_core450.dll"
  )

# Import target "opencv_cudaarithm" for configuration "Release"
set_property(TARGET opencv_cudaarithm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudaarithm PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_cudaarithm450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_cudaarithm450.dll"
  )

# Import target "opencv_flann" for configuration "Release"
set_property(TARGET opencv_flann APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_flann PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_flann450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_flann450.dll"
  )

# Import target "opencv_imgproc" for configuration "Release"
set_property(TARGET opencv_imgproc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_imgproc PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_imgproc450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_imgproc450.dll"
  )

# Import target "opencv_intensity_transform" for configuration "Release"
set_property(TARGET opencv_intensity_transform APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_intensity_transform PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_intensity_transform450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_intensity_transform450.dll"
  )

# Import target "opencv_ml" for configuration "Release"
set_property(TARGET opencv_ml APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_ml PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_ml450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_ml450.dll"
  )

# Import target "opencv_phase_unwrapping" for configuration "Release"
set_property(TARGET opencv_phase_unwrapping APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_phase_unwrapping PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_phase_unwrapping450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_phase_unwrapping450.dll"
  )

# Import target "opencv_plot" for configuration "Release"
set_property(TARGET opencv_plot APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_plot PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_plot450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_plot450.dll"
  )

# Import target "opencv_quality" for configuration "Release"
set_property(TARGET opencv_quality APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_quality PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_quality450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_quality450.dll"
  )

# Import target "opencv_reg" for configuration "Release"
set_property(TARGET opencv_reg APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_reg PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_reg450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_reg450.dll"
  )

# Import target "opencv_surface_matching" for configuration "Release"
set_property(TARGET opencv_surface_matching APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_surface_matching PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_surface_matching450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_surface_matching450.dll"
  )

# Import target "opencv_cudafilters" for configuration "Release"
set_property(TARGET opencv_cudafilters APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudafilters PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_cudafilters450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_cudafilters450.dll"
  )

# Import target "opencv_cudaimgproc" for configuration "Release"
set_property(TARGET opencv_cudaimgproc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudaimgproc PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_cudaimgproc450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_cudaimgproc450.dll"
  )

# Import target "opencv_cudawarping" for configuration "Release"
set_property(TARGET opencv_cudawarping APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudawarping PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_cudawarping450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_cudawarping450.dll"
  )

# Import target "opencv_dnn" for configuration "Release"
set_property(TARGET opencv_dnn APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_dnn PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_dnn450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_dnn450.dll"
  )

# Import target "opencv_dnn_superres" for configuration "Release"
set_property(TARGET opencv_dnn_superres APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_dnn_superres PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_dnn_superres450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_dnn_superres450.dll"
  )

# Import target "opencv_features2d" for configuration "Release"
set_property(TARGET opencv_features2d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_features2d PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_features2d450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_features2d450.dll"
  )

# Import target "opencv_fuzzy" for configuration "Release"
set_property(TARGET opencv_fuzzy APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_fuzzy PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_fuzzy450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_fuzzy450.dll"
  )

# Import target "opencv_hfs" for configuration "Release"
set_property(TARGET opencv_hfs APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_hfs PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_hfs450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_hfs450.dll"
  )

# Import target "opencv_img_hash" for configuration "Release"
set_property(TARGET opencv_img_hash APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_img_hash PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_img_hash450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_img_hash450.dll"
  )

# Import target "opencv_imgcodecs" for configuration "Release"
set_property(TARGET opencv_imgcodecs APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_imgcodecs PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_imgcodecs450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_imgcodecs450.dll"
  )

# Import target "opencv_line_descriptor" for configuration "Release"
set_property(TARGET opencv_line_descriptor APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_line_descriptor PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_line_descriptor450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_line_descriptor450.dll"
  )

# Import target "opencv_photo" for configuration "Release"
set_property(TARGET opencv_photo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_photo PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_photo450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_photo450.dll"
  )

# Import target "opencv_saliency" for configuration "Release"
set_property(TARGET opencv_saliency APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_saliency PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_saliency450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_saliency450.dll"
  )

# Import target "opencv_text" for configuration "Release"
set_property(TARGET opencv_text APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_text PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_text450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_text450.dll"
  )

# Import target "opencv_videoio" for configuration "Release"
set_property(TARGET opencv_videoio APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_videoio PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_videoio450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_videoio450.dll"
  )

# Import target "opencv_xphoto" for configuration "Release"
set_property(TARGET opencv_xphoto APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_xphoto PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_xphoto450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_xphoto450.dll"
  )

# Import target "opencv_calib3d" for configuration "Release"
set_property(TARGET opencv_calib3d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_calib3d PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_calib3d450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_calib3d450.dll"
  )

# Import target "opencv_cudacodec" for configuration "Release"
set_property(TARGET opencv_cudacodec APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudacodec PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_cudacodec450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_cudacodec450.dll"
  )

# Import target "opencv_cudafeatures2d" for configuration "Release"
set_property(TARGET opencv_cudafeatures2d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudafeatures2d PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_cudafeatures2d450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_cudafeatures2d450.dll"
  )

# Import target "opencv_cudastereo" for configuration "Release"
set_property(TARGET opencv_cudastereo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudastereo PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_cudastereo450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_cudastereo450.dll"
  )

# Import target "opencv_datasets" for configuration "Release"
set_property(TARGET opencv_datasets APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_datasets PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_datasets450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_datasets450.dll"
  )

# Import target "opencv_highgui" for configuration "Release"
set_property(TARGET opencv_highgui APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_highgui PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_highgui450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_highgui450.dll"
  )

# Import target "opencv_mcc" for configuration "Release"
set_property(TARGET opencv_mcc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_mcc PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_mcc450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_mcc450.dll"
  )

# Import target "opencv_objdetect" for configuration "Release"
set_property(TARGET opencv_objdetect APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_objdetect PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_objdetect450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_objdetect450.dll"
  )

# Import target "opencv_rapid" for configuration "Release"
set_property(TARGET opencv_rapid APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_rapid PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_rapid450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_rapid450.dll"
  )

# Import target "opencv_rgbd" for configuration "Release"
set_property(TARGET opencv_rgbd APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_rgbd PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_rgbd450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_rgbd450.dll"
  )

# Import target "opencv_shape" for configuration "Release"
set_property(TARGET opencv_shape APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_shape PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_shape450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_shape450.dll"
  )

# Import target "opencv_structured_light" for configuration "Release"
set_property(TARGET opencv_structured_light APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_structured_light PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_structured_light450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_structured_light450.dll"
  )

# Import target "opencv_video" for configuration "Release"
set_property(TARGET opencv_video APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_video PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_video450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_video450.dll"
  )

# Import target "opencv_xfeatures2d" for configuration "Release"
set_property(TARGET opencv_xfeatures2d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_xfeatures2d PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_xfeatures2d450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_xfeatures2d450.dll"
  )

# Import target "opencv_ximgproc" for configuration "Release"
set_property(TARGET opencv_ximgproc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_ximgproc PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_ximgproc450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_ximgproc450.dll"
  )

# Import target "opencv_xobjdetect" for configuration "Release"
set_property(TARGET opencv_xobjdetect APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_xobjdetect PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_xobjdetect450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_xobjdetect450.dll"
  )

# Import target "opencv_aruco" for configuration "Release"
set_property(TARGET opencv_aruco APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_aruco PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_aruco450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_aruco450.dll"
  )

# Import target "opencv_bgsegm" for configuration "Release"
set_property(TARGET opencv_bgsegm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_bgsegm PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_bgsegm450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_bgsegm450.dll"
  )

# Import target "opencv_bioinspired" for configuration "Release"
set_property(TARGET opencv_bioinspired APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_bioinspired PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_bioinspired450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_bioinspired450.dll"
  )

# Import target "opencv_ccalib" for configuration "Release"
set_property(TARGET opencv_ccalib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_ccalib PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_ccalib450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_ccalib450.dll"
  )

# Import target "opencv_cudabgsegm" for configuration "Release"
set_property(TARGET opencv_cudabgsegm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudabgsegm PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_cudabgsegm450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_cudabgsegm450.dll"
  )

# Import target "opencv_cudalegacy" for configuration "Release"
set_property(TARGET opencv_cudalegacy APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudalegacy PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_cudalegacy450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_cudalegacy450.dll"
  )

# Import target "opencv_cudaobjdetect" for configuration "Release"
set_property(TARGET opencv_cudaobjdetect APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudaobjdetect PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_cudaobjdetect450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_cudaobjdetect450.dll"
  )

# Import target "opencv_dnn_objdetect" for configuration "Release"
set_property(TARGET opencv_dnn_objdetect APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_dnn_objdetect PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_dnn_objdetect450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_dnn_objdetect450.dll"
  )

# Import target "opencv_dpm" for configuration "Release"
set_property(TARGET opencv_dpm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_dpm PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_dpm450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_dpm450.dll"
  )

# Import target "opencv_face" for configuration "Release"
set_property(TARGET opencv_face APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_face PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_face450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_face450.dll"
  )

# Import target "opencv_gapi" for configuration "Release"
set_property(TARGET opencv_gapi APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_gapi PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_gapi450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_gapi450.dll"
  )

# Import target "opencv_optflow" for configuration "Release"
set_property(TARGET opencv_optflow APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_optflow PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_optflow450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_optflow450.dll"
  )

# Import target "opencv_stitching" for configuration "Release"
set_property(TARGET opencv_stitching APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_stitching PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_stitching450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_stitching450.dll"
  )

# Import target "opencv_tracking" for configuration "Release"
set_property(TARGET opencv_tracking APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_tracking PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_tracking450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_tracking450.dll"
  )

# Import target "opencv_cudaoptflow" for configuration "Release"
set_property(TARGET opencv_cudaoptflow APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudaoptflow PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_cudaoptflow450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_cudaoptflow450.dll"
  )

# Import target "opencv_stereo" for configuration "Release"
set_property(TARGET opencv_stereo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_stereo PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_stereo450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_stereo450.dll"
  )

# Import target "opencv_superres" for configuration "Release"
set_property(TARGET opencv_superres APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_superres PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_superres450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_superres450.dll"
  )

# Import target "opencv_videostab" for configuration "Release"
set_property(TARGET opencv_videostab APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_videostab PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/lib/Release/opencv_videostab450.lib"
  IMPORTED_LOCATION_RELEASE "D:/Study/Python/Lib/opencv-4.5.0/build/bin/Release/opencv_videostab450.dll"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
